name: Load Google Datasets

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '55 23 30 4,6,9,11'
    - cron: '55 23 31 1,3,5,7,8,10,12'
    - cron: '55 23 28 2'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml
