name: Load Google Datasets

on:
  push:
    branches:
        - "function_test"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file .github/workflows/environment.yml
      - name: Run migrations
        run: python .github/workflows/dataset_scraper
        env:
          XML_LINK: ${{ vars.XML_LINK }}
